export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const UPDATE_CART = "UPDATE_CART";
export const TOGGLE_CART = "TOGGLE_CART";
export const TOGGLE_MOBILE_MENU = "TOGGLE_MOBILE_MENU";
